Russian translation fix
Aninoss/lawliet-web pull request #18
Opened 2024-03-02 18:36 UTC by fckn-clown

I reviewed the entire file and manualy fixed almost all the mistakes.
Feel free to ask any questions and check everything by yourself.

2024-03-02 19:09 UTC, NeverCookFirst reviewed
`dash.getpremium = Получить премиум` - is the right

2024-03-02 19:10 UTC, NeverCookFirst commented on src/main/resources/translate_ru.properties
> +category.privacy = Выходные данные & Политика Конфиденциальности
`Выходные данные & Политика конфиденциальности`

2024-03-02 19:11 UTC, NeverCookFirst commented on src/main/resources/translate_ru.properties
> +err.exception.des = Произошла серверная ошибка. Пожалуйста, повторите попытке позже!
`err.exception.des = Произошла серверная ошибка. Пожалуйста, повторите попытку позже!`

2024-03-03 09:38 UTC, NeverCookFirst requested changes
yes

2024-03-03 09:38 UTC, NeverCookFirst commented on src/main/resources/translate_ru.properties
> +category.privacy = Выходные данные & Политика Конфиденциальности
`category.privacy = Выходные данные & Политика конфиденциальности`

2024-03-03 20:50 UTC, fckn-clown commented on src/main/resources/translate_ru.properties
> +err.404.title = 404 Страница не найдена
Could you please explain this one for me? 
Why there should be a comma and the error code name should be lowercase? 

I mean it's literally the full error code name "404 Страница не найдена" ("404 Not Found") and it always was like that.
If it's necessary then we could maybe change it to something like "Ошибка 404\nСтраница не найдена" ("Error 404\nPage not found").

2024-03-03 20:53 UTC, fckn-clown commented
> `dash.getpremium = Получить премиум` - is the right

Could you please explain this one for me?
Why "Premium" in this one should be in lowercase if it's name of the feature?

2024-03-06 09:41 UTC, NeverCookFirst commented on src/main/resources/translate_ru.properties
> +err.404.title = 404 Страница не найдена
> Could you please explain this one for me? Why there should be a comma and the error code name should be lowercase?
> 
> I mean it's literally the full error code name "404 Страница не найдена" ("404 Not Found") and it always was like that. If it's necessary then we could maybe change it to something like "Ошибка 404\nСтраница не найдена" ("Error 404\nPage not found").

согласен

2024-03-06 09:42 UTC, NeverCookFirst commented
> > `dash.getpremium = Получить премиум` - is the right
> 
> Could you please explain this one for me? Why "Premium" in this one should be in lowercase if it's name of the feature?

потому что в русском языке такие правила, не пишутся Вот Так Слова, это грубо

2024-03-17 08:29 UTC, merged